#!/bin/bash

# Script usage/help/error strings
S_SCRIPTNAME="mountrepo"
S_USAGE="Usage: mountrepo [OPTIONS]\nTry 'mountrepo help' for more information."
S_USAGE_EXTENDED="Usage: mountrepo [OPTIONS]\nOPTIONS is a url identifying a valid svn repo."
S_HELP=$S_SCRIPTNAME" \"mounts\" a remote Subversion repository,\nallowing you to peruse it as you would a local file system."
S_SVN_NOT_INSTALLED="mountrepo: requires Subversion VCS."
S_MOUNT_ERROR="mountrepo: unable to \"mount\" repo. Subversion reports:"

# Error codes
E_SUCCESS=0
E_ERROR=-1

# SVN usage strings
CD_CMD="cd"
DOT_CMD="."
DOTDOT_CMD=".."
LS_CMD="ls"
LS_R_CMD="ls -R"
PWD_CMD="pwd"
CLEAR_CMD="clear"
EXIT_CMD="exit"

# Escape characters
IFS_ORIG="$IFS"
IFS=""
TAB_CHAR=`printf "\t"`
ENTER_CHAR=`printf "\n"`
ESC_SEQ=$'\x1b'
UP_ARROW=$'\x1b[A'
DOWN_ARROW=$'\x1b[B'
LEFT_ARROW=$'\x1b[D'
RIGHT_ARROW=$'\x1b[C'
DELETE_CHAR=$'\x7f'

BACKSPACE="\b"
CLEAR_LINE_RIGHT="\x1b[K"
CLEAR_LINE="\x1b[2K"

if [ -z $1 ]
then
	echo -e "$S_USAGE"
	exit $E_ERROR
fi

if [ "$1" == "help" ] || [ "$1" == "--help" ]
then
	echo -e "$S_HELP"
	echo -e "$S_USAGE_EXTENDED"
	exit $E_SUCCESS
fi

# check svn installed
SVN_LOC=$(whereis svn)
if [ "$SVN_LOC" == "svn:" ]
then
	echo -e "$S_SVN_NOT_INSTALLED"
	exit $E_ERROR
fi

# check valid svn repo
SVN_REPO_URL=$1
err=$(svn info "$SVN_REPO_URL" 2>&1)
if [ $? -ne 0 ]
then
	echo -e "$S_MOUNT_ERROR"
	echo -e "$err"
	exit $E_ERROR
fi

cmd_stack[0]=""
cmd_stack_len=0
cmd_stack_index=0

# 'mount' it!
CURR_BROWSE_LOC=$SVN_REPO_URL
while true
do
	cmd=""
	cmd_stack_index=$((cmd_stack_len))
	printf "$CURR_BROWSE_LOC""$ "
	while true
	do
		read -s -n1 key
		case "$key" in
			"$TAB_CHAR")
				break
			;;
			"$ENTER_CHAR")
				cmd_stack[$cmd_stack_len]="$cmd"
				((cmd_stack_len++))
				break
			;;
			"$ESC_SEQ")
				read -s -n2 escp # read rest of escape sequence
				seq=$key$escp
				# printf "$CLEAR_LINE\r"
				# printf "$CURR_BROWSE_LOC""$ ""${cmd_stack["$cmd_stack_index"]}"
				if [ "$seq" == "$UP_ARROW" ]; then
					if [ "$cmd_stack_index" -gt 0 ]; then
						((cmd_stack_index--))
					fi
				elif [ "$seq" == "$DOWN_ARROW" ]; then
					if [ "$cmd_stack_index" -lt $((cmd_stack_len-1)) ]; then
						((cmd_stack_index++))
					fi
				fi

				printf "$CLEAR_LINE\r"
				printf "$CURR_BROWSE_LOC""$ ""${cmd_stack["$cmd_stack_index"]}"
				cmd="${cmd_stack["$cmd_stack_index"]}"
			;;
			"$DELETE_CHAR")
				cmd_len=`expr length "$cmd"`
				if [ "$cmd_len" -gt 0 ]
				then
					printf "$BACKSPACE""$CLEAR_LINE_RIGHT"
					cmd=${cmd:0:$cmd_len-1}
				fi
			;;
			*)
				printf "$key"
				cmd="$cmd""$key"
			;;	
		esac	
	done
	printf "\n"
	if [ "${cmd:0:2}" == $CD_CMD ] 
	then
		len=`expr length "$cmd"`
		dir=${cmd:3:$len}
		if [ "$dir" == $DOT_CMD ]; then
			continue
		elif [ "$dir" == $DOTDOT_CMD ]; then
			len_curr_loc=`expr length "$CURR_BROWSE_LOC"`
			last_char=`expr substr "$CURR_BROWSE_LOC" "$len_curr_loc" 1`
			CURR_BROWSE_LOC=${CURR_BROWSE_LOC%/*$last_char}
			continue
		elif [ "$dir" == "" ]; then
			CURR_BROWSE_LOC="$SVN_REPO_URL"
			continue
		fi

		err=$(svn info "$CURR_BROWSE_LOC"/"$dir" 2>&1)
		if [ $? -ne 0 ] 
		then
			printf "mountrepo: cd: "$dir": No such file or directory\n"
			continue
		fi

		isDir=$(echo "$err" | grep "directory")
		if [ $? -eq 1 ] 
		then
			printf "mountrepo: cannot 'mount' file, only directories\n"
		else
			CURR_BROWSE_LOC="$CURR_BROWSE_LOC"/"$dir"
		fi
	else
		case "$cmd" in
			"$LS_CMD")
				ls_res=`svn ls $CURR_BROWSE_LOC`
				echo ${ls_res//$'\n'/' '} # replace newline characters
			;;
			"$LS_R_CMD")
				svn ls $CURR_BROWSE_LOC --depth infinity
			;;
			"$PWD_CMD")
				echo "$CURR_BROWSE_LOC"
			;;
			"$CLEAR_CMD")
				clear
			;;
			"$EXIT_CMD")
				exit $E_SUCCESS
			;;
			*) # pass any unrecognized commands off to svn	
				svn "$cmd" $CURR_BROWSE_LOC
			;;
		esac
	fi	
done
